# Generated by Django 4.0.3 on 2022-10-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='memo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='codigo',
            field=models.CharField(default='Q3SN+Q', max_length=10, unique=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='contra',
            field=models.CharField(default='ivi', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='creador',
            field=models.CharField(default='Diosito', max_length=100),
        ),
        migrations.AddField(
            model_name='todo',
            name='dia',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='todo',
            name='fcompleted',
            field=models.IntegerField(default=0),
        ),
    ]
