# Generated by Django 4.1.2 on 2022-10-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_todo_created_remove_todo_memo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='private',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='codigo',
            field=models.CharField(default='8sUGcg', max_length=10, unique=True),
        ),
    ]
